name: GH env test
on:
  push:
    branches:
      - gh-env-test

jobs:
  expo-build:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v3
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
          echo "with_space=hello world" >> "$GITHUB_ENV"
          echo "with_space_quoted=\"hello world\"" >> "$GITHUB_ENV"
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'
          printf '%s\n' "$with_space" # This will output 'hello'
          printf '%s\n' "$with_space_quoted" # This will output 'hello world'
